quarkus.virtual-threads.enabled=true

quarkus.live-reload.enabled=false
quarkus.profile=prod

quarkus.datasource.db-kind=other
quarkus.datasource.jdbc.driver=org.sqlite.JDBC
quarkus.datasource.jdbc.url=jdbc:sqlite:data/chaos-xcom-launcher-sqlite.db
quarkus.datasource.username=
quarkus.datasource.password=
#SQLite supports maximum 1 connection to file, but actually multiple reads are supported
#quarkus.datasource.jdbc.min-size=10
#quarkus.datasource.jdbc.max-size=10

#quarkus.liquibase.migrate-at-start=true
#quarkus.liquibase.validate-on-migrate=true
#quarkus.liquibase.change-log=db/migration/migrations.xml
#quarkus.liquibase.enabled=true

quarkus.flyway.migrate-at-start=true
quarkus.flyway.enabled=true
quarkus.flyway.locations=classpath:db/migration

# steam
client.steam/mp-rest/connectTimeout=5000
client.steam/mp-rest/readTimeout=10000